language: python

python:
    - "3.6"

install:
    # flake8: static analysis and style checks against PEP8
    - pip install -U flake8
    - pip install -U flake8-bugbear
    - pip install -U flake8-docstrings

script:
    # Static analysis
    - flake8 .
